=== abarhub/eiffel/test_unitaire/context.dtd
<!ELEMENT liste_classe (classe)>
<!ELEMENT classe (erreur*)>
<!ATTLIST classe nom CDATA #REQUIRED>

<!ELEMENT erreur (#PCDATA)>
<!ATTLIST erreur nom CDATA #REQUIRED>

=== abarhub/eiffel/test/context/Copie de test_context.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE liste_classe SYSTEM "..\..\test_unitaire\context.dtd">
<liste_classe>
<!--	<classe nom=".\test\test8.e">
		<erreur nom="ErreurVEEN">L'attribut j n'est pas declare dans la classe TEST8 a la ligne (16,15,.\test\test8.e)</erreur>
		<erreur nom="ErreurVUEX1">L'attribut f n'est pas declaré dans la classe TEST8 à la ligne (17,12,.\test\test8.e)</erreur>
		<erreur nom="ErreurVEEN">L'attribut j n'est pas declare dans la classe TEST8 a la ligne (18,17,.\test\test8.e)</erreur>
		<erreur nom="ErreurVUEX1">L'attribut infix "and" n'est pas declaré dans la classe INTEGER à la ligne (19,14,.\test\test8.e)</erreur>
		<erreur nom="ErreurVJAR">Dans la classe TEST8, l'affectation a la ligne (32,9,.\test\test8.e) est incorrecte, car BOOLEAN n'est pas conforme a INTEGER</erreur>
		<erreur nom="ErreurVMCN2">conflit pour l'attribut Void dans la classe TEST8 entre l'héritage ANY à la ligne (3,1,.\test\test8.e) et l'attribut à la ligne (22,9,.\test\test8.e)</erreur>
		<erreur nom="ErreurVUAR2">Le parametre numero 1 de type BOOLEAN n'est pas conforme avec le parametre formel de type INTEGER pour l'appel  a la ligne (33,24,.\test\test8.e) de la classe TEST8 et la declaration a la ligne (13,27,.\std_classe\INTEGER.e) de la classe INTEGER pour la fonction infix "+"</erreur>
	</classe>
	<classe nom=".\test\test9.e">
	</classe>
	< !- -<classe nom=".\test\test10.e">
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur dans l'instruction</erreur>
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur dans le corps de l'attribut</erreur>
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur dans l'attribut</erreur>
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur dans le nom d'attribut</erreur>
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur dans la classe</erreur>
		<erreur nom="ErreurSource">Erreur .\test\test10.e(11,11) : Erreur de parsing:Erreur Parse (11,15):Il faut !</erreur>
	</classe>- - >
	<classe nom="test\context\vdrs2\test1.e">
		<erreur nom="ErreurVDRS2">Dans la classe TEST1 l'attribut a herite de TOTO1 est redefinie a la ligne (3,9,test\context\vdrs2\test1.e) alors qu'il est frozen a la ligne (5,9,test\context\vdrs2\TOTO1.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs2\test2.e">
	</classe>
	<classe nom="test\context\vmcn2\test1.e">
		<erreur nom="ErreurVMCN2">conflit pour l'attribut Void dans la classe TEST1 entre l'héritage ANY à la ligne (3,9,test\context\vmcn2\test1.e) et l'attribut à la ligne (7,9,test\context\vmcn2\test1.e)</erreur>
	</classe>
	<classe nom="test\context\vmcn3\test1.e">
		<erreur nom="ErreurVMCN3">conflit pour l'attribut hello dans la classe TEST1entre les heritages B et A aux lignes (3,9,test\context\vmcn3\test1.e) et (3,9,test\context\vmcn3\test1.e)</erreur>
	</classe>
	<classe nom="test\context\vmcn3\test2.e">
	</classe>
	<classe nom="test\context\vmcn3\test3.e">
		<erreur nom="ErreurVMCN3">conflit pour l'attribut hello dans la classe TEST3entre les heritages B et D aux lignes (3,9,test\context\vmcn3\test3.e) et (3,9,test\context\vmcn3\test3.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test1.e">
	</classe>
	<classe nom="test\context\vdrs4\test2.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST2 l'attribut a hérité de A est déclaré redéfinie à la ligne (3,9,test\context\vdrs4\test2.e) mais ne l'est pas effectivement</erreur>
	</classe>
	<classe nom="test\context\vhpr\test1.e">
		<erreur nom="ErreurVHPR">Erreur: il y a un cycle d'heritage (TEST1->...->A->TEST1)</erreur>
	</classe>
	<classe nom="test\context\vhpr\test2.e">
	</classe>
	<classe nom="test\context\vffd2\test1.e">
	</classe>
	<classe nom="test\context\vffd2\test2.e">
		<erreur nom="ErreurVFFD2">Dans la classe TEST2, l'attribut val2 est defini plusieurs fois ((5,14,test\context\vffd2\test2.e) et (9,9,test\context\vffd2\test2.e))</erreur>
	</classe>
	<classe nom="test\context\vffd4\test1.e">
		<erreur nom="ErreurVFFD4">L'attribut d est deferred, et frozen dans la classe TEST1((8,9,test\context\vffd4\test1.e))</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST1 a des attributs deferred a la ligne (8,9,test\context\vffd4\test1.e)</erreur>
	</classe>
	<classe nom="test\context\vffd4\test2.e">
		<erreur nom="ErreurVFFD4">L'attribut i est deferred, et frozen dans la classe A((5,9,test\context\vffd4\A.e))</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST2 a des attributs deferred a la ligne (5,9,test\context\vffd4\A.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete A a des attributs deferred a la ligne (5,9,test\context\vffd4\A.e)</erreur>
	</classe>
	<classe nom="test\context\vdrd5\test1.e">
		<erreur nom="ErreurVDRD5">Impossible de redefinir l'attribut effectif toto a la ligne (3,9,test\context\vdrd5\test1.e) en un attribut deferred a la ligne (9,9,test\context\vdrd5\test1.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST1 a des attributs deferred a la ligne (9,9,test\context\vdrd5\test1.e)</erreur>
	</classe>
	<classe nom="test\context\vmcn2\test2.e">
		<erreur nom="ErreurVMCN2">conflit pour l'attribut tata dans la classe TEST2 entre l'héritage A à la ligne (3,9,test\context\vmcn2\test2.e) et l'attribut à la ligne (7,9,test\context\vmcn2\test2.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST2 a des attributs deferred a la ligne (7,9,test\context\vmcn2\test2.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test6.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST6 l'attribut affiche hérité de C est déclaré redefini à la ligne (3,9,test\context\vdrs4\test6.e) alors que c'est une concrétisation</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete C a des attributs deferred a la ligne (5,9,test\context\vdrs4\C.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test7.e">
		<erreur nom="ErreurVCCH1">La classe concrete C a des attributs deferred a la ligne (5,9,test\context\vdrs4\C.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test3.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST3 l'attribut a hérité de B est déclaré redéfinie à la ligne (3,9,test\context\vdrs4\test3.e) mais ne l'est pas effectivement</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST3 a des attributs deferred a la ligne (5,9,test\context\vdrs4\B.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete B a des attributs deferred a la ligne (5,9,test\context\vdrs4\B.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test4.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST4 l'attribut a hérité de B n'est pas redéclaré à la ligne (3,9,test\context\vdrs4\test4.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST4 a des attributs deferred a la ligne (7,9,test\context\vdrs4\test4.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete B a des attributs deferred a la ligne (5,9,test\context\vdrs4\B.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test5.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST5 l'attribut a hérité de B est déclaré redefini à la ligne (3,9,test\context\vdrs4\test5.e) alors que c'est une concrétisation</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete B a des attributs deferred a la ligne (5,9,test\context\vdrs4\B.e)</erreur>
	</classe>
	<classe nom="test\context\vdus3\test1.e">
	</classe>
	<classe nom="test\context\vdus3\test2.e">
		<erreur nom="ErreurVDUS3">Erreur dans la classe TEST2 a la ligne (3,9,test\context\vdus3\test2.e) : l'attribut undefine donne n'est pas concret dans la classe B a la ligne (5,9,test\context\vdus3\B.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete B a des attributs deferred a la ligne (5,9,test\context\vdus3\B.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs2\test3.e">
		<erreur nom="ErreurVDRS2">Dans la classe TEST3 l'attribut var1 herite de A est redefinie a la ligne (3,9,test\context\vdrs2\test3.e) alors qu'il est constant a la ligne (5,9,test\context\vdrs2\A.e)</erreur>
		<erreur nom="ErreurVDRS2">Dans la classe TEST3 l'attribut cst2 herite de A est redefinie a la ligne (3,9,test\context\vdrs2\test3.e) alors qu'il est constant a la ligne (6,9,test\context\vdrs2\A.e)</erreur>
	</classe>
	<classe nom="test\context\vdrs4\test8.e">
		<erreur nom="ErreurVDRS4">Dans la classe TEST8 l'attribut affiche hérité de C n'est pas redéclaré à la ligne (3,9,test\context\vdrs4\test8.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete TEST8 a des attributs deferred a la ligne (8,9,test\context\vdrs4\test8.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete C a des attributs deferred a la ligne (5,9,test\context\vdrs4\C.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete D a des attributs deferred a la ligne (5,9,test\context\vdrs4\D.e)</erreur>
	</classe>
	<classe nom="test\context\vmcn1\test1.e">
		<erreur nom="ErreurVMCN1">conflit pour l'attribut deferred toto dans la classe TEST1entre les heritages B et A aux lignes (3,9,test\context\vmcn1\test1.e) et (3,9,test\context\vmcn1\test1.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete A a des attributs deferred a la ligne (5,9,test\context\vmcn1\A.e)</erreur>
		<erreur nom="ErreurVCCH1">La classe concrete B a des attributs deferred a la ligne (5,9,test\context\vmcn1\B.e)</erreur>
	</classe>
	<classe nom="test\context\vncs1\test1.e">
		<erreur nom="ErreurVNCS1">Le nombre de parametre de toto dans la classe TEST1 ne correspond pas a celui de l'ancetre A aux lignes (9,9,test\context\vncs1\test1.e) et (6,9,test\context\vncs1\A.e)</erreur>
	</classe>
	<classe nom="test\context\vncs1\test2.e">
	</classe>
	<classe nom="test\context\vncs2\test1.e">
		<erreur nom="ErreurVNCS2">Le parametre numero 1 de l'attribut hello dans la classe TEST1 de type REAL n'est pas conforme a DOUBLE_REF de l'ancetre A aux lignes (9,9,test\context\vncs2\test1.e) et (5,9,test\context\vncs2\A.e)</erreur>
	</classe>
	<classe nom="test\context\vncs2\test2.e">
	</classe>
	<classe nom="test\context\vncs2\test3.e">
